### ISSUE TITLE
Try catches every error

### ISSUE THREAD

**Issue by laurent-thiebaud-gisaia** [aol/cyclops#1048]
Hi,

I have the following code:

```
Try.runWithCatch(() -> {
//some processing throwing runtime exception
                }, InterruptedException.class)
                .onFail(InterruptedException.class, e -> {
                    noError.set(false);
                    LOGGER.error(e.getMessage(), e);
                });
```

In my understanding, it should only catch InterruptedException. I realised that it also catches  a ClassCastException (a RuntimeException), but it does not execute the onFail block. It simply catches the exception without doing anything with it. This is a silent exception, I find it very dangerous. The Java native exception handling is safer for me (not compile if an exception if not handled, and only catch the expected exception).

Am I missing something or how to avoid this behavior?

**Comment by johnmcclean** [comment]
Hi @laurent-thiebaud-gisaia,

I agree, Try shouldn't catch this exception if it is not an InterruptedException. That is a bug. 

What version are you using? In 10.3.0 the code below results in a ClassCastException being thrown

```java
	@Test
    public void catchall(){
        Try.runWithCatch(() -> {
            throw new ClassCastException("hello");
//some processing throwing runtime exception
        }, InterruptedException.class)
            .onFail(InterruptedException.class, e -> {
               System.out.println("failed");
            });
        System.out.println("caught");
    }
```

Prints out : 

```
java.lang.ClassCastException: hello

	at cyclops.control.TryTest.lambda$catchall$5(TryTest.java:50)
	at cyclops.control.Try.runWithCatch(Try.java:885)
	at cyclops.control.TryTest.catchall(TryTest.java:49)
```

Which is the expected behaviour. 

Thanks for raising this, does my example cover your case?

**Comment by johnmcclean** [comment]
Closing.
