### ISSUE TITLE
performance and design in xMatch

### ISSUE THREAD

**Issue by lihy70** [aol/cyclops#1050]
Please look at below sample:
```
ReactiveSeq.range(0, 32).peek(System.out::println).peek(i -> {
  try {
    TimeUnit.MILLISECONDS.sleep(1000);
  } catch (InterruptedException e) {
    e.printStackTrace();
  }
}).xMatch(3, i -> true);
```
No need to continue further counting when it's already bigger than the specified `num`.
Would suggest to add `limit` in below code:
```
 return stream.filter(t -> c.test(t))
                     limit(num + 1L).collect(java.util.stream.Collectors.counting()) == num;
```

An additional question about design: what about `atLeast` and/or `atMost` matches?
maybe add a method?
```
boolean xMatch(int atLeast, int atMost, Predicate<? super T> c)
```

**Comment by johnmcclean** [comment]
xMatch currently checks the exact number of matches - atLeast and atMost are good ideas. Short circuiting would convert xMatch into atLeast (and no longer confirm an exact match), so I think we need a new operator to support this.

**Comment by johnmcclean** [comment]
Merged
