### ISSUE TITLE
Adding contributing guidelines

### ISSUE THREAD

**Issue by pepijno** [aol/cyclops#1054]
Thanks for the awesome library!

Can a guideline on contributing to the project be added? Some document about branching rules, code styling, unit tests etc could improve the code quality and help new users contribute to the project.

**Comment by johnmcclean** [comment]
Great idea!

Let's add a CONTRIBUTING.md with some guidelines and information on how to get started!

**Comment by johnmcclean** [comment]
@pepijno Initial Contributing.MD : https://github.com/aol/cyclops/blob/master/CONTRIBUTING.md
