### ISSUE TITLE
Option.onEmpty

### ISSUE THREAD

**Issue by ayush-finix** [aol/cyclops#1055]
I feel like it would make sense to have the symmetric peek method for an empty option. I'd use it for logging (like most peek, onFail, etc methods). Doing a conversion to another wrapper seems a bit wasteful.

**Comment by johnmcclean** [comment]
Seems reasonable. Either has peekLeft, so peekNone makes sense.

**Comment by johnmcclean** [comment]
Looking at the code, I think your naming is better - I think we should go with it.

```java
opt.onEmpty(()->log.info("empty!"));
opt.peekNone(()->log.info("empty!"));
```

**Comment by johnmcclean** [comment]
Merged
