### ISSUE TITLE
Canonical way to split a list of either/try

### ISSUE THREAD

**Issue by ayush-finix** [aol/cyclops#1088]
There are a lot of cases where I end up with a list of Try/Either and I care about partitioning this into the list of success and list of failures.

Is there an equivalent to Either.partitionEithers http://hackage.haskell.org/package/base-4.4.1.0/docs/Data-Either.html?

**Comment by johnmcclean** [comment]
You can use splitBy, which is present on ImmutableList, ImmutableQueue, ImmutableSortedSet and ReactiveSeq to do this.

But we should add a static convenience method on Either also.

**Comment by ayush-finix** [comment]
My only issue with split by is that the signature doesn't quite unpack the datatypes (which is totally reasonable/expected for a generic split by).
```Seq<Either<A, B>>.splitBy -> Tuple2<Seq<Either<A, B>>, Seq<Either<A, B>>>```
instead of
```Seq<Either<A, B>>.eitherSplitBy->Tuple2<Seq<A>, Seq<B>>```
Right now, I'm just manually accumulating.

**Comment by ayush-finix** [comment]
As a related question, is there a pattern for not only splitting the response try/either but also keeping the original request with it?

something where
function: request -> Try<Response, Exception>
List<Request> requests.map(func)->??????->Tuple2<List<Tuple2<Request, Response>>, List<Tuple2<Request, Exception>>>

**Comment by johnmcclean** [comment]
Added partitionEithers, lefts, rights as static methods to the Either class.

**Comment by johnmcclean** [comment]
Merged.
