### ISSUE TITLE
Correctly apply covariance (? extends C) and contravariance (? super C) on generic method type usage

### ISSUE THREAD

**Issue by lukaseder** [aol/cyclops#143]
I've seen this a couple of times across your API:

```java
<C extends Comparable<C>> Optional<T> minBy(Function<T,C> f);
```

E.g. here:
https://github.com/aol/cyclops/blob/49550625800994329e4793f96bb39b5278a431c3/cyclops-sequence-api/src/main/java/com/aol/cyclops/sequence/SequenceM.java#L790

There are some things that are not optimal here. A better API would look like this:

```java
<C extends Comparable<? super C>> Optional<T> minBy(Function<? super T, ? extends C> f);
//                 1: ^^^^^^^^^                           2: ^^^^^^^^^  ^^^^^^^^^^^: 3
```

Here's why:

1. If you have a `Comparable` but non-final type `C`, that type can have subtypes `C1`, `C2`, which are also `Comparable<C>`, not `Comparable<C1>` and `Comparable<C2>`. It is rare to do this for `Comparables` (to be non-final), but in case that's happening, your current signature would force the call-site to do some unnecessary type casting.
2. If a SequenceM<Integer> is used, I would be forced to have `Function<Integer, ?>` as an argument. If my very potent function also accepts `Number`, such as `Function<Number, ?>`, then I couldn't pass that to the method.
3. See also 1.

This image explains it nicely:

![image](https://cloud.githubusercontent.com/assets/734593/12265988/c792c932-b940-11e5-8ece-7c8b4fa5a3cb.png)

See also: http://stackoverflow.com/a/19739576/521799

**Comment by johnmcclean-aol** [comment]
Thanks for this Lukas, that's very helpful. I've modified some of the places already for 7.1.0, some will have to wait until 7.2.0.

**Comment by johnmcclean-aol** [comment]
This is pretty much done for SequenceM and a number of other apis (+ any new ones). Will close this and keep an eye out for future optimisations.
