### ISSUE TITLE
Some maven repositories not accessible

### ISSUE THREAD

**Issue by The-Royal-We** [aol/cyclops#18]
Hey
I'm running  IntelliJ Ultimate Edition on Ubuntu 15.04 and I came across errors when trying to download test dependencies.

It appears that cmmaven.aol.com is being declared in the cyclops-core package and http://repo.bodar.com is being declared in cyclops-converters.
Both of the above sources are not accessible

**Comment by johnmcclean-aol** [comment]
Fixed on Master
