### ISSUE TITLE
blocking transfer queue does not slow producing stream?

### ISSUE THREAD

**Issue by the-james-burton** [aol/cyclops#198]
Hi John,

Fantastic looking library this! I'm just starting to explore it. I'm working through your [user guide](http://gist.asciidoctor.org/?github-aol/simple-react//user-guide/streams.adoc) and trying things out in a sandbox project, starting with simple streams.

I tried stream **example 7 "applying back pressure"** but I found that the producer does not appears to be slowed when the given blocking queue is full.

My test class is [here](https://github.com/the-james-burton/sandbox/blob/master/fp/src/test/java/cyclops/react/StreamsTest.java) and the test is repeated below (almost identical to your example)...

```java
  @Test
  public void testHotStreamsBackPressure() {

    Executor exec = Executors.newFixedThreadPool(1);
    ArrayBlockingQueue<String> blockingQueue = new ArrayBlockingQueue<String>(3);

    ReactiveSeq.range(0, Integer.MAX_VALUE)
        .limit(500)
        .map(i -> i.toString())
        .peek(logger::info)
        .hotStream(exec)
        .connect(blockingQueue)
        .onePer(1, TimeUnit.SECONDS)
        .forEach(next -> logger.info(next));
  }
```

What I see is that the 'peek' above prints all 500 immediately, and then the 'forEach' at the end prints one per second. Is this expected? 

Thanks,
James

**Comment by johnmcclean-aol** [comment]
Hi James,

Thanks  a million for reporting this. I can replicate this issue thanks to your test, and have been able to identify the problem very quickly.

NonPausableHotStream#init and PausableHotStream#init are both using 


      connections.get(i).offer(a);

Calling offer on a BlockingQueue results in it returing false if full immediately. 

Calling add on the other hand blocks until space is available. I'll get this fixed and a release out ASAP!

Thanks again!

**Comment by the-james-burton** [comment]
You're welcome, glad to be of help!

I'm working through the examples and if I spot anything else, I'll let you know.

**Comment by the-james-burton** [comment]
Just FYI... I'll ask my general questions about cyclops-react on stackoverflow.com. Hopefully, that will increase publicity for this library a bit as well as making it easy for others to find answers.

I've just asked one now, but I don't have enough rep to create a 'cyclops-react' tag, so I will prefix my questions with 'cyclops-react' instead and tag them with the existing 'simple-react' tag.

If I do spot a bug, feel free to ask me to raise an issue here. I'm also happy to PR doc corrections if that would help.

**Comment by johnmcclean-aol** [comment]
Good idea with the StackOverflow - really appreciate that.

This bug on cyclops-react issue tracker will track this issue - https://github.com/aol/cyclops-react/issues/204
