### ISSUE TITLE
Multiple Matchers in the same isMatch method.

### ISSUE THREAD

**Issue by marcocast** [aol/cyclops#22]
in the ElementCase
is possible to add a method :
public  <V> InMatchOfBuilder<V,X> isMatch(Matcher<V>... matches) ?
so that i can do something like :
.when().isMatch(startsWith("ERROR") && containsString("NullPointerException"))

I can achieve the same at the moment using the org.hamcrest.core.AllOf.allOf

isMatch(allOf(startsWith("ERROR"), containsString("NullPointerException")))

but I think It would be nice and helpful to have it as native feature in cyclops

**Comment by marcocast** [comment]
Fixed 
public <V> InMatchOfBuilder<V, X> isMatch(Matcher<V>... matches) {

		return new InMatchOfBuilder<V, X>(allOf(matches), patternMatcher, this);
	}

**Comment by johnmcclean-aol** [comment]
So..

     Matching.when().isMatch(allOf(startsWith("ERROR"),containsString("NullPointerException"))) 

To compose with and And

And

    Matching.when().isMatch(anyOf(startsWith("ERROR"),containsString("NullPointerException"))) 

To compose with an Or

There is also CombinableMatcher which as and, or, either methods : http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/core/CombinableMatcher.html

**Comment by marcocast** [comment]
should I remove the new method from ElementCase and leave the user to decide how to combine multiple matchers?

**Comment by johnmcclean-aol** [comment]
No, didn't realise you had added a method. It's a good idea. Make the purpose more clear in the name (allMatch). anyMatch and noneMatch might also be good too.

**Comment by marcocast** [comment]
Added also allMatch, anyMatch and noneMatch

**Comment by johnmcclean-aol** [comment]
Closing issue solution on Master
