### ISSUE TITLE
Create cyclops-typeclasses

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops#228]
Implement support for derive4j HKT types in cyclop-react.  See https://github.com/aol/cyclops-react/issues/347

Provide a basic set of Type Class interfaces along with a Generalized implementation 

e.g. 

``` java
    interface Functor<CRE>{

        public <T,R> Higher<CRE,R> map(Function<? super T,? extends R> fn, Higher<CRE,T> ds);

    }
```

Can be implemented in a specific for ListX (for example) - note abandoning the use of the inner µ type for semantic witness class names (in order to decouple the witness type from the core type).

``` java
interface ListFunctor extends Functor<ListType.listx>{

            @Override
            default <T, R> ListType<R> map(Function<? super T,? extends R> fn, Higher<ListType.listx, T> functor){
                return narrow(functor).map(fn);
            }
        }
```

``` java
static  ListFunctor listFunctor(){

            return new ListFunctor(){};
}
```

Allowing code like this 

``` java
ListX<Integer> listx = ListX.of(1,2,3);
ListType<Integer> mapped1 =listFunctor().map(a->a+1, listx);
mapped1.add(1);
listApplicative().ap(ListX.of(a->a*2),ListX.of(1,2,3));
```

Could be generalized something like this 

``` java
       @AllArgsConstructor
        static class GeneralFunctor<CRE,A> implements Functor<CRE>{
            Function<Higher<CRE,?>,A> narrowFn;
            BiFunction<A,Function,Higher<CRE,?>> mapRef;
            Function<A,Higher<CRE,?>> widenFn;

            @Override
            public <T,R> Higher<CRE,R> map(Function<? super T,? extends R> fn, Higher<CRE,T> ds){
                return (Higher<CRE, R>) widenFn.apply(mapRef.apply(narrowFn.apply(ds),fn));
            }
        }
        static  <CRE,A> GeneralFunctor<CRE,A> functor(Function<Higher<CRE,?>,A> narrowFn, BiFunction<A,Function,Higher<CRE,?>>  f,Function<A,Higher<CRE,?>> widenFn){

            return new GeneralFunctor<>(narrowFn,f,widenFn);

        }
```

Which would allow us to directly reuse a set of generic Type Classes across any / all of the functional libraries for Java.

All other cyclops-modules should inherit from cyclops-typeclasses. If / when HighJ is released as an open source project, a more complete set could be imported from there.

**Comment by johnmcclean-aol** [comment]
If the type being used doesn't implement the HKT interface more conversions are neccessary

```java
ListX<Integer> listx = ListX.of(1,2,3);
ListType<Integer> mapped1 =listFunctor().map(a->a+1, widen(listx));
mapped1.narrow()
                .add(1);

```

**Comment by johnmcclean-aol** [comment]
Higher<T1,T2> can't extend from HKT.__<T1,T2> as the type processor expects / forces it to have 

```java
public static final class µ {}
```

Which means generalizing witness types for 3rd party libraries for derive4j HKT types is awkward or impossible (which from the perspective of the purpose of the library means it is doing it's job :) ).

**Comment by johnmcclean-aol** [comment]
If Higher is defined in the package org.derive4j.hkt it can alias __ safely without impacting the preprocessor.

Need to check if that makes sense (aliasing), one alternative is have the concrete Type Constructor type (e.g. ListType) implement both __ and Higher rather than the core type (e.g. ListX). That way ListType can simulate higher kinded types for java.util.List as well as for ListX and can be used with HighJ via __ or Higher can be used separately  where more verbose semantic naming is prefered.

**Comment by johnmcclean-aol** [comment]
Call implementations can be greatly simplified if Higher adds an apply method
e.g. 
```java
 default <T, R> ListType<R> map(Function<? super T,? extends R> fn, Higher<ListType.listx, T> functor){
    return ListType.widen(ListType.narrow(functor).map(fn));
}
```

could become something like ( removing the need for widen and narrow)

```java
 default <T, R> Higher<ListType.listx, R> map(Function<? super T,? extends R> fn, Higher<ListType.listx, T> functor){
   return functor.apply(ListFns::map,fn);
}
```

**Comment by jbgi** [comment]
With last hkt release (0.9) you should now be able to move `Higher` out of `org.derive4j.hkt`.

**Comment by johnmcclean-aol** [comment]
Awesome thanks JB!

**Comment by johnmcclean-aol** [comment]
Merged

**Comment by jbgi** [comment]
there was a bug in the 0.9 release, so you may want to upgrade to 0.9.1 that should reach maven central soon.
