### ISSUE TITLE
Incorrect return type parameter for Try.flatten()

### ISSUE THREAD

**Issue by sgoeminn** [aol/cyclops#258]
The following code is expected to compile. However, it returns a Try<Try<String, Throwable>, Throwable>>. 
`Try<String, Throwable> r = Try.of(Try.of("r")).flatten();`

Expecting interface to specify a type similar to the return type of flatMap:
`public <R> Try<R,X> flatten()`
with two implicit cases:
* T = R
* T instance of Try<S, X>, unwrapped until S = R

**Comment by johnmcclean-aol** [comment]
Hey @sgoeminn, which version are you using? The latest cyclops-react 2.x has a static flatten method that can be used as follows

        Try<String, Throwable> r = Try.of(Try.of("r")).to(Try::flatten);

This is guaranteed to be type-safe. We can backport this to standalone cyclops-try if needed.

**Comment by sgoeminn** [comment]
I'm using version 7.2.3 (http://static.javadoc.io/com.aol.cyclops/cyclops-try/7.2.3/com/aol/cyclops/trycatch/Try.html#flatten--)

**Comment by johnmcclean-aol** [comment]
Released in https://github.com/aol/cyclops/releases/tag/v7.2.4
