### ISSUE TITLE
ClassCastException when trying to create a monad instance with AnyM#unit()

### ISSUE THREAD

**Issue by smillies** [aol/cyclops#61]
The following unit tests fail with a ClassCastException. I would expect `unit()` to create an instance of the underlying monad (an Optional or a List) in each case, but that does not seem to happen.

	@Test
	public void unitOptional() {
		AnyM<Integer> empty = AnyMonads.anyM(Optional.empty());
		AnyM<Integer> unit = empty.unit(1);
		Optional<Integer> unwrapped = unit.unwrap();
		assertEquals(Integer.valueOf(1), unwrapped.get());
	}

	@Test
	public void unitList() {
		AnyM<Integer> empty = AnyMonads.anyM(Collections.emptyList());
		AnyM<Integer> unit = empty.unit(1);
		List<Integer> unwrapped = unit.asSequence().toList();
		assertEquals(Integer.valueOf(1), unwrapped.get(0));
	}

**Comment by johnmcclean-aol** [comment]
@smillies  Thanks for this. Yes, that's the expected behaviour. I'll look into this today.

**Comment by johnmcclean-aol** [comment]
PR : https://github.com/aol/cyclops/pull/63

**Comment by johnmcclean-aol** [comment]
Fixed in 6.0.4
