### ISSUE TITLE
ExceptionSoftener can lead to ClassCastException

### ISSUE THREAD

**Issue by earlzero** [aol/cyclops#62]
Right now `ExceptionSoftener` in cyclops-invokedynamic always trying to cast any exception to `RuntimeException` in method `ExceptionSoftener.uncheck`. In case that any exception, that is "softened" is not subclass of `RuntimeException` it will lead to `ClassCastException` between this exception class and `RuntimeException`. Possible fix is to change implementation of `throwSoftenedException`
to something like
` throw new RuntimeException(e);`

**Comment by johnmcclean-aol** [comment]
Thanks Nikita. There's a little bit of compiler trickier going on here. Possibly there are some cases which we have missed. I'm not sure if you have found a failing test or are analysiing the code. I've added a unit test with a few passing examples - you can take a look here : https://github.com/aol/cyclops/blob/master/cyclops-invokedynamic/src/test/java/com/aol/cyclops/invokedynamic/ExceptionSoftenerTest.java

**Comment by earlzero** [comment]
I was analysing the code. I think that JUnit interpret resulting exception as class which was set in "expected" attribute. Almost all of your test are expecting other types of exception (except `runtime`), so if any code will try to interpret result of `throwSoftenedException` as RuntimeException - it will fail.

I wrote additional testcase
http://pastebin.com/TDCz3tyr
which is failing. You can see that result of `throwSoftenedException` is of class `IOException`, so it isn't RuntimeException.

**Comment by johnmcclean-aol** [comment]
Yeah it doesn't actually create a RuntimeException, it just makes the compiler treat a checked Exception as an unchecked on. I think Throwables in Guava might behave in the way you are expecting.
