### ISSUE TITLE
Surprising behaviour of convertToAnyM with List

### ISSUE THREAD

**Issue by smillies** [aol/cyclops#67]
I have seen you have added a new ListComprehender - thank you very much. However, there still seems to be no uniform way of converting Optional or List to AnyM and unwrapping to what one put in.AsAnyM.convertToAnyM (and AnyMonads.anyM) will still convert a List to a Stream (SequenceImpl).

I would find it more natural if they kept the List, because there is a Comprehender for it. However, the behavior may be more efficient, as you note in your 6.1.0 release comments. I'd still prefer it to be changed. What do you think?

**Comment by johnmcclean-aol** [comment]
If you use convertToAnyM it will always try to do the conversion. You have a couple of options to directly push a List or Optional into an AnyM with the same method and avoid the conversion.

1. You can use AsAnyM.notTypeSafeAnyM(list/optional)
2. AnyM itself now has some creational methods and here AnyM.ofMonad(list/optional) is the one you want.

```java
@Test
	public void createAnyMFromListOrOptional(){
		List<Integer> list = Arrays.asList(1,2,3);
		assertThat(AnyM.ofMonad(list).unwrap(),instanceOf(List.class));
		Optional<Integer> opt = Optional.of(1);
		assertThat(AnyM.ofMonad(opt).unwrap(),instanceOf(Optional.class));
	}
	@Test
	public void createAnyMFromListOrOptionalAsAnyM(){
		List<Integer> list = Arrays.asList(1,2,3);
		assertThat(AsAnyM.notTypeSafeAnyM(list).unwrap(),instanceOf(List.class));
		Optional<Integer> opt = Optional.of(1);
		assertThat(AsAnyM.notTypeSafeAnyM(opt).unwrap(),instanceOf(Optional.class));
	}
```

**Comment by smillies** [comment]
Thanks for your help, again.

I must say, this is not an easy library to learn. Cyclops contains a host of conversion functions. To mention just a few there is AnyMonads.anyM, AsAnyM.convertToAnyM, or AnyM.ofMonad and lots more. Javdoc is sparse, and it is really difficult to know when to use what method.This is not an easy library to learn.

Could this be consolidated a bit? I guess that's an enhancement request.

**Comment by johnmcclean-aol** [comment]
Great point. 

I think so, AsAnyM should be deprecated and replaced with the creational methods on AnyM - I think that is simpler - what do you think? 

(Also point taken no javadoc on the new creational methods in AnyM).

**Comment by smillies** [comment]
Yes, I think that would be a step in the right direction. It would mean, however, that Cyclops would be using a deprecated API internally, possibly generating unnecessary compiler warnings, so perhaps AnyMFactoryImpl could delegate to a new version of AsAnyM that would be placed somewhere below com.aol.cyclops.internal.

And perhaps it would also be possible to deprecate those methods from AnyMonads that appear to duplicate functionality from AnyM, basically AnyMonads.anyM* ?

**Comment by johnmcclean-aol** [comment]
Agreed.

**Comment by johnmcclean-aol** [comment]
API changes being tracked in this issue : https://github.com/aol/cyclops/issues/70
