### ISSUE TITLE
flatMap does not work as expected with ListComprehender

### ISSUE THREAD

**Issue by smillies** [aol/cyclops#68]
Monad wrappers around lists with the new factory methods involving the native ListComprehender do not flatMap as expected. The follwoing test fails with 

java.lang.ClassCastException: java.util.stream.ReferencePipeline$Head cannot be cast to java.util.List at com.aol.cyclops.comprehensions.comprehenders.ListComprehender.lambda$executeflatMap$29(ListComprehender.java:30)
	

	@Test
    public void flatMapWithListComprehender() {
        List<Integer> list = Arrays.asList(1,2,3);
        AnyM<Integer> any = AsAnyM.anyMList(list); 
        AnyM<Integer> mapped = any.flatMap(e -> any.unit(e));
        List<Integer> unwrapped = mapped.unwrap();
        assertEquals(list, unwrapped);
    }

**Comment by johnmcclean-aol** [comment]
Thanks for this - I've added this unit test and it passes locally for me (against the cyclops source that should have gone in to 6.1.0) - I'm going to check it directly against the current 6.1.0 to confirm the issue.

I've added your test here : https://github.com/aol/cyclops/blob/master/cyclops-monad-api/src/test/java/com/aol/cyclops/lambda/monads/AnyMTest.java

**Comment by johnmcclean-aol** [comment]
I can replicate this issue running from the jar file. Working on a fix.

**Comment by johnmcclean-aol** [comment]
fixed in cyclops 6.1.1

List Comprehension is more efficient in 6.1.1 also

@Test
public void flatMapWithListComprehender() {
    List<Integer> list = Arrays.asList(1,2,3);
    AnyM<Integer> any =  AnyM.fromList(list); 
    AnyM<Integer> mapped = any.flatMap(e -> any.unit(e));
    List<Integer> unwrapped = mapped.unwrap();
    assertEquals(list, unwrapped);
}
