### ISSUE TITLE
Deprecate all AnyM creational methods and add equivalents on AnyM itself

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops#70]
Too many ways to instantiate AnyM, make the creational methods available on the interface.

Add appropriate Javadoc for each one.

**Comment by smillies** [comment]
Shameless plug: I've written up an example of using the new 6.1.1 functionality here:
http://sebastian-millies.blogspot.de/2015/11/deterministic-and-non-deterministic.html
Perhaps you're interested.

**Comment by johnmcclean-aol** [comment]
Cool - will have a detailed read of that later today!

**Comment by smillies** [comment]
That would be nice. I just wanted to add, if you see anything that is incorrect, please leave a comment and I will correct it. For example, it just came to me that I'm not really sure if any of those factory methods would still implicitly convert a list to a stream.

**Comment by johnmcclean-aol** [comment]
Remove deprecated methods in 7.0.0

**Comment by johnmcclean-aol** [comment]
Released in v7.0.0 of cyclops
