### ISSUE TITLE
Passing Class<X>... varargs parameter causes "Unchecked generics array creation" warning

### ISSUE THREAD

**Issue by laszlovandenhoek** [aol/cyclops#790]
Varargs are just syntactic sugar for arrays, so using them in combination with generic types, this will always make the compile emit an "Unchecked generics array creation" warning if you call these methods. This happens in several places in cyclops-react.

For example, the four `Fn0`..`Fn3` implementations in `cyclops.function.FluentFunctions` (i.e. `FluentSupplier`, `FluentFunction`, `FluentBiFunction` and `FluentTryFunction`) all have a `liftTry` method taking a vararg `Class<X>` argument. Of course, we know this is safe, but perhaps there is a better way. I can think of a few:
- providing several overloaded forms (for one `Class<X>`, for two, for three, ...)
- adding a fluent API to call once for every `Class<X>`

This is not a huge problem, but having to add `@SuppressWarnings("unchecked")` hurts a little every time I do it.

**Comment by johnmcclean** [comment]
Thanks @laszlovandenhoek we can make liftTry final and add a Safevarargs annotation. I think that should solve this problem - at least for liftTry.  Are there any other methods that are causing this problem that you are aware of?

**Comment by laszlovandenhoek** [comment]
That's great! I was referring to some methods in `Try` but I didn't know about `@SafeVarargs`, so it looks like there's no problem there. I haven't done a thorough check though.

**Comment by johnmcclean** [comment]
We have to add it directly on to the problem methods on Try so we'll still need to fix. Which version are you using and we can add a fix there too?

**Comment by laszlovandenhoek** [comment]
I meant that I was only looking at the code for `Try`; I assumed wrongly that if the methods there contained `Class<X>...` parameters then that would cause issues - I didn't actually check. However, all those methods have a `@SafeVarargs` in place already in the 2.1.1 I'm using. So, again, the problem seems contained to `FluentFunctions`.

**Comment by laszlovandenhoek** [comment]
Found another couple in `Try` itself:
- `success`
- `mapOrCatch`
- `flatMapOrCatch`
- `withResources` (2 of 'em)

**Comment by johnmcclean** [comment]
@laszlovandenhoek @Safevarargs added to those methods in the milestone 7 release.
