### ISSUE TITLE
Create static methods for partial application of functions / method refs

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops#9]
Similar to the Curry class, except partially apply rather than Curry.

E.g. 

      public static <T1,T2,T3,T4,R> BiFunction<T3,T4,R>>>>  partial4(T1 t1, T2 t2, QuadFunction<T1,T2,T3,T4,R> quadFunc){
		return   ( t3 ,t4) -> quadFunc.apply(t1,t2,t3,t4);
	}

**Update** : Is this better? Or worse?

      public static <T1,T2,T3,T4,R>  BiFunction<T1,T2,BiFunction<T3,T4,R>>>>>  partial4(  QuadFunction<T1,T2,T3,T4,R> quadFunc){
		return   ( t3 ,t4) -> quadFunc.apply(t1,t2,t3,t4);
	}

I think the first way may be better, as in terms of method naming and variable signatures it is simpler.

**Comment by The-Royal-We** [comment]
I'll take a look at this John (It's Brendan from work on my student git a/c)

**Comment by johnmcclean-aol** [comment]
Excellent thanks Brendan!

**Comment by The-Royal-We** [comment]
Merged to master
