### ISSUE TITLE
Mutation operations on immutable JDK collections should throw UnsupportedOperationException

### ISSUE THREAD

**Issue by seanf** [aol/cyclops#910]
The JavaDoc contracts for JDK Collection mutation operations (eg [`java.util.List.add()`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#add-E-)) state that the methods will throw `UnsupportedOperationException` if the operation is not supported. This behaviour helps to expose programming errors as early as possible (ie when accidentally passing an immutable collection where a mutable collection is expected). 

The JDK Collection view classes (like [ListView](https://github.com/aol/cyclops-react/blob/6cc74dd3b6eada39da9039253319ce3ebc3e7ed6/cyclops/src/main/java/com/oath/cyclops/types/persistent/views/ListView.java#L91)) don't throw `UnsupportedOperationException` as specified by the Collection contracts; instead they silently ignore mutations.

By way of reference, Dexx and Paguro both appear to respect the contract in their immutable `java.util.List` implementations:

- https://github.com/andrewoma/dexx/blob/a685e4c29ec5ac6126f337dbf7f1d493d2af7bd0/collection/src/main/java/com/github/andrewoma/dexx/collection/internal/adapter/ListAdapater.java#L77
- https://github.com/GlenKPeterson/Paguro/blob/0b2496953c365455e4d6e8a15da0d7a0846f0de0/src/main/java/org/organicdesign/fp/collections/UnmodList.java#L80

**Comment by johnmcclean** [comment]
Released in 10.0.1
