### ISSUE TITLE
takeWhile/takeUntil inclusive/exclusive

### ISSUE THREAD

**Issue by ayush-finix** [aol/cyclops#959]
Currently, takewhile/takeuntil appear to be exclusive. I was wondering if it would be possible to enhance the api to add the inclusive version of the methods.

ex.
take until exclusive
[t, t, f].takeUntil(p -> p) = [t, t]
take until inclusive
[t, t, f].takeUntil(p -> p) = [t, t, f]

take while exclusive
[f, t, t].takeWhile(p->p) = []
take while inclusive
[f, t, t].takeWhile(p->p) = [f]

In my own search, this seems to not have a good non-library solution, as a few examples:
https://github.com/ReactiveX/rxjs/issues/2420
https://stackoverflow.com/questions/41741681/haskell-takewhile-1

**Comment by johnmcclean** [comment]
Yes, this is a good idea. There is code in place to do this already (LimitWhileClosedSpliterator for Iterable data structures and LimitWhileClosedOperator for reactive-streams) so we should expose this in the API. Any thoughts on the method names?

```java
takeWhileInclusive
takeWhileInc
 ```
We should do this for dropWhile / dropUntil aswell

**Comment by ayush-finix** [comment]
As much as we like pretending this isn't java, it is, with all the verbose method names and all; =P. I'd just use the full `Inclusive` and let everyone's favorite ides autocomplete it.

I could see boolean parameters being a possibility as well (though I'm not a big fan and would much rather a new method name), but there's nothing that strictly stops `takeWhile(Predicate, boolean)` from existing.

**Comment by johnmcclean** [comment]
I've added two child stories to this Epic for release in 10.1.0 which is to add these operators to ReactiveSeq. It means it will be available on all of the core types via
```java
myInstance.stream()
          .takeWhileInclusive(this::condition)
          .to(XXXX::fromterable);
```

We can leave this Epic open to track the conversation around adding these operators to other types directly.

**Comment by johnmcclean** [comment]
Closing this epic - for now.

**Comment by vitaly-t** [comment]
This doesn't seem right...

* `takeWhile` must always be exclusive, based on linguistic logic
* `skipWhile` must always be inclusive, based on linguistic logic

The `until` logic is supposed to complete the scope by reversing that:

* `takeUntil` must be inclusive
* `skipUntil` must be exclusive

Then you have a full range of logic covered.
